swarm:
  security:
    security-domains:
      test-realm:
        jaspi-authentication:
          login-module-stacks:
            test-login-module-stack:
              login-modules:
              - login-module: jwt-login-module
                code: org.wildfly.swarm.microprofile.jwtauth.deployment.auth.jaas.JWTLoginModule
                flag: required
          auth-modules:
            http:
              code: org.wildfly.extension.undertow.security.jaspi.modules.HTTPSchemeServerAuthModule
              module: org.wildfly.extension.undertow
              flag: required
              login-module-stack-ref: test-login-module-stack
